import "@/shared/styles/display.directions.css"
import "@/shared/styles/display.positions.css"
import "@/shared/styles/font.sizes.css"
import "@/shared/styles/font.weights.css"
import "@/shared/styles/image.sizes.css"
import "@/shared/styles/spacing.css"
import "@/shared/styles/primevue.modifications.css"
import "@/shared/styles/vanishes.appears.css"
import "@/shared/styles/grid.css"
import "@/shared/styles/animations.css"
import "@/shared/styles/transforms.css"
import "@/shared/styles/main.css"
import "primeicons/primeicons.css"
export default 0